import contextlib
import math
import random
import time
from pathlib import Path
import numpy as np
import torch
from .common import save, read, environment
from .data import Crops, class_weights, split, TestImages
from .evaluate import autocast, precision, evaluate, predict
from .losses import loss_fn


def seed_all(seed):
    random.seed(seed); np.random.seed(seed); torch.manual_seed(seed)
    if torch.cuda.is_available(): torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.benchmark = False
    torch.backends.cudnn.deterministic = True


def rng_state():
    return {'python': random.getstate(), 'numpy': np.random.get_state(),
            'torch': torch.get_rng_state(),
            'cuda': torch.cuda.get_rng_state_all() if torch.cuda.is_available() else []}


def restore_rng(state):
    random.setstate(state['python']); np.random.set_state(state['numpy'])
    torch.set_rng_state(state['torch'].cpu())
    if state['cuda'] and torch.cuda.is_available():
        if len(state['cuda']) != torch.cuda.device_count(): raise RuntimeError('CUDA device count changed on resume')
        torch.cuda.set_rng_state_all([x.cpu() for x in state['cuda']])


def atomic_checkpoint(path, value):
    path = Path(path); path.parent.mkdir(parents=True, exist_ok=True)
    temporary = path.with_suffix('.partial.pt')
    torch.save(value, temporary); temporary.replace(path)


def checkpoint_load(path):
    # Only load trusted checkpoints generated by this project; RNG includes Python/NumPy state.
    state = torch.load(path, map_location='cpu', weights_only=False)
    if state.get('format') != 'aic-segformer-v1': raise ValueError('Unknown checkpoint format')
    return state


def optimizer_for(model, c):
    groups = []
    for backbone in (True, False):
        for decay in (True, False):
            params = [p for n,p in model.named_parameters() if p.requires_grad
                      and n.startswith('backbone.') == backbone and (p.ndim > 1) == decay]
            if params:
                lr = c['backbone_lr'] if backbone else c['head_lr']
                groups.append({'params': params, 'lr': lr, 'initial_lr': lr,
                               'weight_decay': c['weight_decay'] if decay else 0.})
    return torch.optim.AdamW(groups)


def set_lr(optimizer, update, total, warmup_fraction):
    warm = max(1, int(total * warmup_fraction))
    factor = (update + 1) / warm if update < warm else max(0., 1 - (update - warm) / max(total - warm, 1)) ** .9
    for group in optimizer.param_groups: group['lr'] = group['initial_lr'] * factor


def loader_for(c, epoch, names, cursor=0):
    order = list(names); random.Random(c['seed'] + epoch).shuffle(order)
    generator = torch.Generator().manual_seed(c['seed'] + epoch)
    return torch.utils.data.DataLoader(Crops(c, epoch, order[cursor:]), batch_size=c['batch_size'],
             shuffle=False, num_workers=c['workers'], pin_memory=True,
             generator=generator, persistent_workers=False, drop_last=False)


def update_group(model, iterator, optimizer, scaler, c, device, samples, weights):
    model.train(); optimizer.zero_grad(set_to_none=True)
    count = 0; losses = 0.
    while count < samples:
        x, y = next(iterator); n = len(x)
        if count + n > samples: raise RuntimeError('Accumulation cursor is not on a batch boundary')
        x, y = x.to(device, non_blocking=True), y.to(device, non_blocking=True)
        with autocast(c, device): value = loss_fn(model(x), y, c, weights)
        if not torch.isfinite(value): raise FloatingPointError('Nonfinite training loss; resume last completed checkpoint')
        scaler.scale(value * (n / samples)).backward()
        losses += float(value.detach()) * n; count += n
    scaler.unscale_(optimizer)
    norm = torch.nn.utils.clip_grad_norm_(model.parameters(), c['grad_clip'], error_if_nonfinite=True)
    before = scaler.get_scale(); scaler.step(optimizer); scaler.update()
    if scaler.get_scale() < before: raise FloatingPointError('AMP update skipped; resume last completed checkpoint')
    return losses / samples, float(norm)


def train(model, c, run, identity, resume=False):
    run = Path(run); device = next(model.parameters()).device
    names = split()['train']; group_size = c['batch_size'] * c['accumulation']
    per_epoch = math.ceil(len(names) / group_size); total = per_epoch * c['epochs']
    optimizer = optimizer_for(model, c)
    scaler = torch.amp.GradScaler('cuda', enabled=precision(c, device) == torch.float16)
    weights = class_weights(c)
    if weights is not None: weights = weights.to(device)
    state = {'epoch': 0, 'cursor': 0, 'update': 0, 'best_miou': -1., 'best_epoch': None}
    seed_all(c['seed'])
    if resume:
        loaded = checkpoint_load(run / 'last.pt')
        if loaded['identity'] != identity: raise RuntimeError('Resume code/config/data/weight identity mismatch')
        if loaded['precision'] != str(precision(c, device)): raise RuntimeError('Resume precision changed')
        for key in ('torch', 'transformers', 'cuda'):
            if loaded['environment'][key] != environment()[key]: raise RuntimeError('Resume environment changed: ' + key)
        model.load_state_dict(loaded['model'], strict=True); optimizer.load_state_dict(loaded['optimizer'])
        scaler.load_state_dict(loaded['scaler']); state = loaded['state']; restore_rng(loaded['rng'])
        del loaded
        print(f'恢复 epoch={state["epoch"]} cursor={state["cursor"]} update={state["update"]}', flush=True)
    if c.get('stop_after_updates') and state['update'] >= c['stop_after_updates']:
        print('断点已达到指定更新数限制；取消该限制后可继续', flush=True)
        return False

    def snapshot(path):
        atomic_checkpoint(path, {'format': 'aic-segformer-v1', 'identity': identity, 'config': c,
             'environment': environment(), 'precision': str(precision(c, device)),
             'model': model.state_dict(), 'optimizer': optimizer.state_dict(), 'scaler': scaler.state_dict(),
             'state': state.copy(), 'scheduler': {'total': total, 'warmup_fraction': c['warmup_fraction'], 'next_update': state['update']},
             'rng': rng_state()})

    started = time.monotonic(); start_update = state['update']
    for epoch in range(state['epoch'], c['epochs']):
        state['epoch'] = epoch
        iterator = iter(loader_for(c, epoch, names, state['cursor']))
        while state['cursor'] < len(names):
            n = min(group_size, len(names) - state['cursor'])
            set_lr(optimizer, state['update'], total, c['warmup_fraction'])
            loss, norm = update_group(model, iterator, optimizer, scaler, c, device, n, weights)
            state['cursor'] += n; state['update'] += 1
            if state['update'] % c['log_every'] == 0 or state['cursor'] == len(names):
                elapsed = time.monotonic() - started
                eta = elapsed / max(state['update'] - start_update, 1) * (total - state['update'])
                print(f'epoch {epoch+1}/{c["epochs"]} samples {state["cursor"]}/{len(names)} update {state["update"]}/{total} loss {loss:.5f} grad {norm:.3f} lr {optimizer.param_groups[0]["lr"]:.3g} 纯训练剩余估计 {eta/3600:.2f} h', flush=True)
            if state['update'] % c['save_every'] == 0: snapshot(run / 'last.pt')
            if c.get('stop_after_updates') and state['update'] >= c['stop_after_updates']:
                snapshot(run / 'last.pt'); print('到达显式更新数限制，已保存可恢复断点', flush=True); return False
        del iterator
        # Save before validation: a disconnection can resume this epoch's validation.
        snapshot(run / 'last.pt')
        if (epoch + 1) % c['validate_every'] == 0 or epoch + 1 == c['epochs']:
            val = evaluate(model, split()['val'], c, run / 'metrics' / f'epoch{epoch+1:03d}_val.json')
            domain = evaluate(model, split()['domain_val'], c, run / 'metrics' / f'epoch{epoch+1:03d}_domain.json')
            if val['miou'] is None or domain['miou'] is None: raise RuntimeError('Validation has no valid pixels')
            if domain['miou'] > state['best_miou']:
                state.update(best_miou=domain['miou'], best_epoch=epoch + 1)
                snapshot(run / 'best.pt')
                save(run / 'best_metrics.json', {'selection': 'highest domain_val mIoU, matching prior project; val diagnostic also reported',
                     'epoch': epoch + 1, 'val': val, 'domain_val': domain, 'official_score': None})
        state['epoch'] = epoch + 1; state['cursor'] = 0
        snapshot(run / 'last.pt')
    save(run / 'completed.json', {'updates': state['update'], 'best_epoch': state['best_epoch'], 'best_domain_miou': state['best_miou'], 'official_score': None})
    return True


def benchmark(model, c, output):
    device = next(model.parameters()).device
    if device.type != 'cuda':
        result = {'environment': environment(), 'device': 'cpu', 'gpu_measured': False,
                  'budget_pass': False, 'note': 'CPU structural check only; no server memory/speed/training claims.'}
        save(output, result); return result
    saved_rng = rng_state()
    # Restore weights too: preflight optimization must not become undeclared training.
    original = {k:v.detach().cpu().clone() for k,v in model.state_dict().items()}
    optimizer = optimizer_for(model, c)
    scaler = torch.amp.GradScaler('cuda', enabled=precision(c, device) == torch.float16)
    weights = class_weights(c)
    if weights is not None: weights = weights.to(device)
    group = c['batch_size'] * c['accumulation']
    wanted = (c['benchmark_updates'] + 2) * group
    names = split()['train']
    if wanted > len(names): raise ValueError('Benchmark exceeds one epoch')
    iterator = iter(loader_for(c, 0, names[:wanted]))
    torch.cuda.reset_peak_memory_stats(device)
    times = []
    try:
        for i in range(c['benchmark_updates'] + 2):
            torch.cuda.synchronize(device); begin = time.monotonic()
            loss, norm = update_group(model, iterator, optimizer, scaler, c, device, group, weights)
            torch.cuda.synchronize(device); duration = time.monotonic() - begin
            print(f'GPU 测速 {i+1}/{c["benchmark_updates"]+2} {duration:.3f} s/update loss={loss:.4f}', flush=True)
            if i >= 2: times.append(duration)
        temp = Path(output).with_suffix('.benchmark.pt')
        begin = time.monotonic()
        atomic_checkpoint(temp, {'model': model.state_dict(), 'optimizer': optimizer.state_dict()})
        checkpoint_seconds = time.monotonic() - begin; checkpoint_bytes = temp.stat().st_size
        temp.unlink()
        del optimizer, iterator
        model.load_state_dict(original, strict=True); model.zero_grad(set_to_none=True)
        torch.cuda.empty_cache()
        inference_times = []
        with TestImages(c) as test:
            for name in test.names[:4]:
                torch.cuda.synchronize(device); begin = time.monotonic()
                predict(model, test.read(name), c)
                torch.cuda.synchronize(device); inference_times.append(time.monotonic() - begin)
        seconds_per_image = float(np.mean(inference_times[1:]))
        peak = torch.cuda.max_memory_allocated(device) / 2**30
        reserved = torch.cuda.max_memory_reserved(device) / 2**30
        updates = math.ceil(len(names) / group) * c['epochs']
        validations = len(set(list(range(c['validate_every'], c['epochs']+1, c['validate_every'])) + [c['epochs']]))
        train_seconds = float(np.mean(times)) * updates
        val_seconds = seconds_per_image * (len(split()['val']) + len(split()['domain_val'])) * validations
        predict_seconds = seconds_per_image * c['expected_test_count']
        save_seconds = checkpoint_seconds * (math.ceil(updates / c['save_every']) + c['epochs'] * 3)
        estimate = (train_seconds + val_seconds + predict_seconds + save_seconds) * 1.2 / 3600
        result = {'environment': environment(), 'device': str(device), 'gpu_measured': True,
                  'config': c, 'optimizer_updates_seconds': times, 'effective_batch': group,
                  'inference_seconds_per_image': seconds_per_image, 'inference_measured_images': 4,
                  'peak_allocated_gib': peak, 'peak_reserved_gib': reserved,
                  'checkpoint_seconds': checkpoint_seconds, 'checkpoint_bytes': checkpoint_bytes,
                  'estimate_train_hours': train_seconds / 3600, 'estimate_validation_hours': val_seconds / 3600,
                  'estimate_prediction_hours': predict_seconds / 3600,
                  'estimate_total_hours_with_20pct_margin': estimate,
                  'budget_pass': estimate <= c['max_hours'] and reserved <= c['max_peak_gib'],
                  'note': 'Short measured benchmark; full-run time is an extrapolation, not a measured result. Peak excludes other processes/driver; sparse validation disk IO may differ.'}
        save(output, result); return result
    finally:
        model.load_state_dict(original, strict=True); model.zero_grad(set_to_none=True); restore_rng(saved_rng)
        torch.cuda.empty_cache()
